language: node_js

node_js:
  - '10'
  - '12'
  - '13'

cache: yarn

before_script:
  - yarn install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test:unit
  - yarn test:lint
  - yarn test:coverage
  - yarn build

after_success:
  - yarn docs:publish
  - ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID -t lcov coverage/lcov.info

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs
  on:
    tags: true

deploy:
  provider: npm
  email: lalung.alexandre@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master

code_climate:
  repo_token:
    secure: encrypted string
